language: node_js
node_js:
  - "8.11.4"

dist: trusty

cache:
  directories:
    - node_modules

env:
  - TEST_DATABASE_URL=postgres://postgres@localhost:5432/sms_api_test

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database sms_api_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
